name: Publish Retype powered website to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to retype branch

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.x

      - uses: retypeapp/action-build@v4

      - uses: retypeapp/action-github-pages@v4
        with:
          update-branch: true
